/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyInput {
    }
    interface MyListItem {
    }
    interface MyMenu {
    }
    interface MyPopover {
    }
    interface MyTimepicker {
    }
}
declare global {
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyListItemElement extends Components.MyListItem, HTMLStencilElement {
    }
    var HTMLMyListItemElement: {
        prototype: HTMLMyListItemElement;
        new (): HTMLMyListItemElement;
    };
    interface HTMLMyMenuElement extends Components.MyMenu, HTMLStencilElement {
    }
    var HTMLMyMenuElement: {
        prototype: HTMLMyMenuElement;
        new (): HTMLMyMenuElement;
    };
    interface HTMLMyPopoverElement extends Components.MyPopover, HTMLStencilElement {
    }
    var HTMLMyPopoverElement: {
        prototype: HTMLMyPopoverElement;
        new (): HTMLMyPopoverElement;
    };
    interface HTMLMyTimepickerElement extends Components.MyTimepicker, HTMLStencilElement {
    }
    var HTMLMyTimepickerElement: {
        prototype: HTMLMyTimepickerElement;
        new (): HTMLMyTimepickerElement;
    };
    interface HTMLElementTagNameMap {
        "my-input": HTMLMyInputElement;
        "my-list-item": HTMLMyListItemElement;
        "my-menu": HTMLMyMenuElement;
        "my-popover": HTMLMyPopoverElement;
        "my-timepicker": HTMLMyTimepickerElement;
    }
}
declare namespace LocalJSX {
    interface MyInput {
    }
    interface MyListItem {
    }
    interface MyMenu {
    }
    interface MyPopover {
    }
    interface MyTimepicker {
    }
    interface IntrinsicElements {
        "my-input": MyInput;
        "my-list-item": MyListItem;
        "my-menu": MyMenu;
        "my-popover": MyPopover;
        "my-timepicker": MyTimepicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-list-item": LocalJSX.MyListItem & JSXBase.HTMLAttributes<HTMLMyListItemElement>;
            "my-menu": LocalJSX.MyMenu & JSXBase.HTMLAttributes<HTMLMyMenuElement>;
            "my-popover": LocalJSX.MyPopover & JSXBase.HTMLAttributes<HTMLMyPopoverElement>;
            "my-timepicker": LocalJSX.MyTimepicker & JSXBase.HTMLAttributes<HTMLMyTimepickerElement>;
        }
    }
}
